### ISSUE TITLE
animplay brakes on retarget

### ISSUE THREAD

**Issue by J-Andersen-UvA** [J-Andersen-UvA/BabylonSignLab#96]
cannot do adding to observables when retarget has been done

**Comment by J-Andersen-UvA** [comment]
see jariNPM
runtimeAnimation.ts:262 
 Uncaught (in promise) 
TypeError: Cannot read properties of null (reading 'influence')
    at e._preparePath (runtimeAnimation.ts:262:33)
    at new e (runtimeAnimation.ts:225:18)
    at e.appendAnimations (animatable.ts:198:41)
    at e (animatable.ts:152:18)
    at rt.beginDirectAnimation (animatable.ts:840:24)
    at a (animationGroup.ts:659:44)
    at e.start (babylon.js:1:1573856)
    at playAnims.js:240:28
    at new Promise (<anonymous>)
    at playAnims (playAnims.js:186:16)
